version: "3.8"

services:
  # Frontend Vue
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    networks:
      - taskmanager-network

  # Backend Laravel 8 (PHP-FPM)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
      - ./backend/vendor:/var/www/html/vendor
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=taskmanager
      - DB_USERNAME=admin
      - DB_PASSWORD=123456
      - JWT_SECRET=NSHUKu3kNNQZF0HiejG6ni0fgwGGcJq0v8m1wOFQWZlkvH6aeyeb64PO4AfxMjKf
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=noreply@taskmanager.com
      - MAIL_FROM_NAME=TaskManager
    depends_on:
      - postgres
      - mailhog
    networks:
      - taskmanager-network

  # Worker para filas do Laravel
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres
      - mailhog
    networks:
      - taskmanager-network

  # Servidor Web (Nginx)
  nginx:
    image: nginx:1.21
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - taskmanager-network

  # PostgreSQL Database
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskmanager-network

  # MailHog
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - taskmanager-network

volumes:
  postgres_data:

networks:
  taskmanager-network:
    driver: bridge
